/* eslint-disable @typescript-eslint/no-unsafe-assignment */
/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable @typescript-eslint/no-unsafe-return */
/* eslint-disable @typescript-eslint/no-misused-promises */
import { Button, ButtonGroup, Card, Container, Heading, Spinner } from "@chakra-ui/react";
import axios from "axios";
import Head from "next/head";
import { useRouter } from "next/router";
import { useQuery } from "react-query";
import SalesList from "~/components/entities/sales/SalesList";
import { AppHeader } from "~/components/global/AppHeader";

import { env } from "~/env.mjs";


export default function Home() {
  const { data: sales, isLoading } = useQuery({
    queryKey: ['sales'], queryFn: async () => {
      const res = await axios.get(`${env.NEXT_PUBLIC_BACKEND_BASE_URL}/sales`,
        { withCredentials: true })
      return res.data.data
    }
  })
  const router = useRouter();
  return (
    <>
      <Head>
        <title>AdminApp</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container marginTop={8}>
        <AppHeader />
        <Card p={4}>
          <Heading>Sales</Heading>
          {isLoading ?
            <Spinner
              thickness='4px'
              speed='0.65s'
              emptyColor='gray.200'
              color='blue.500'
              size='xl'
            /> :
            <SalesList sales={sales} />}
          <ButtonGroup mt={8}>
            <Button
              colorScheme="purple"
              onClick={() => router.push('/clients')}
            >
              Clients
            </Button>
            <Button
              colorScheme="blue"
              onClick={() => router.push('/sales/new')}
            >
              New Sale
            </Button>
          </ButtonGroup>
        </Card>
      </Container>
    </>
  );
}
